# Generated by Django 5.2.12 on 2026-06-29 09:09

import apps.evidence.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_alter_case_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_STORAGE', 'In Storage'), ('WITH_ANALYST', 'With Analyst'), ('ANALYSIS_COMPLETE', 'Analysis Complete')], default='COLLECTED', max_length=25)),
                ('submitted_to_storage_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_evidence_items', to='cases.case')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officer_evidence_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('evidence_file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.evidence.models.evidence_upload_path)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10)),
                ('sha256_hash', models.CharField(editable=False, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_files', to='evidence.evidence')),
            ],
            options={
                'db_table': 'evidence_files',
            },
        ),
    ]
