# Generated by Django 5.2.12 on 2026-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
