# Generated by Django 5.2.12 on 2026-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
