# Generated by Django 5.2.12 on 2026-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
