# Generated by Django 5.2.12 on 2026-06-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_batch_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='batch_number',
            new_name='badge_number',
        ),
    ]
