# Generated by Django 5.2.12 on 2026-06-30 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('FINDING_CREATED', 'Finding Created'), ('FINDING_SUBMITTED', 'Finding Submitted')], default='FINDING_CREATED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='evidence.evidence')),
            ],
            options={
                'db_table': 'findings',
                'constraints': [models.UniqueConstraint(fields=('evidence', 'version_number'), name='unique_evidence_version')],
            },
        ),
    ]
