# Generated by Django 5.2.12 on 2026-06-29 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('CASE_SUBMITTED_TO_STORAGE', 'Case Submitted to Storage'), ('CASE_IN_STORAGE', 'Case In Storage'), ('CASE_WITH_ANALYST', 'Case With Analyst'), ('CASE_UNDER_REVIEW', 'Case Under Review'), ('CASE_SENT_TO_COURT', 'Case Sent to Court'), ('CASE_CLOSED', 'Case Closed'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('EVIDENCE_ANALYSIS_COMPLETE', 'Evidence Analysis Complete'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=36)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audits_entity__557a11_idx'), models.Index(fields=['actor'], name='audits_actor_i_8a17b9_idx'), models.Index(fields=['timestamp'], name='audits_timesta_30b5f9_idx')],
            },
        ),
    ]
