# Generated by Django 5.2.12 on 2026-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('CASE_SUBMITTED_TO_STORAGE', 'Case Submitted to Storage'), ('CASE_IN_STORAGE', 'Case In Storage'), ('CASE_WITH_ANALYST', 'Case With Analyst'), ('CASE_UNDER_REVIEW', 'Case Under Review'), ('CASE_SENT_TO_COURT', 'Case Sent to Court'), ('CASE_CLOSED', 'Case Closed'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('EVIDENCE_FILE_UPLOADED', 'Evidence File Uploaded'), ('EVIDENCE_ANALYSIS_COMPLETE', 'Evidence Analysis Complete'), ('FINDING_CREATED', 'Finding Created'), ('FINDING_SUBMITTED', 'Finding Submitted')], max_length=100),
        ),
    ]
