# Generated by Django 5.2.12 on 2026-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('EVIDENCE_FILE_UPLOADED', 'Evidence File Uploaded'), ('CASE_SUBMITTED_TO_STORAGE', 'Case Submitted to Storage'), ('CASE_IN_STORAGE', 'Case In Storage'), ('CASE_WITH_ANALYST', 'Case With Analyst'), ('FINDING_CREATED', 'Finding Created'), ('FINDING_SUBMITTED', 'Finding Submitted'), ('CASE_SENT_TO_COURT', 'Case Sent to Court'), ('CASE_CLOSED', 'Case Closed')], max_length=100),
        ),
    ]
